
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "secure-api.fullname" . }}
  labels:
    {{- include "secure-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "secure-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
