{{- if .Values.azureSecretsProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "secure-api.fullname" . }}
  labels:
    {{- include "secure-api.labels" . | nindent 4 }}
spec:
  provider: azure
  {{- if .Values.azureSecretsProvider.secretObjects }}
  secretObjects:
    {{ toYaml .Values.azureSecretsProvider.secretObjects | indent 4 }}
  {{- end }}

  parameters:
    usePodIdentity: {{ .Values.azureSecretsProvider.usePodIdentity | default true | quote }}
    keyvaultName: {{ .Values.azureSecretsProvider.keyVaultName }}              # the name of the KeyVault
    objects: {{ toYaml .Values.azureSecretsProvider.secrets | indent 4 }}
    tenantId: {{ .Values.azureSecretsProvider.tenant }}      
{{- end }}
